# coding: utf-8

"""
SearchServiceApi.py
Copyright 2016 SmartBear Software

   Licensed under the Apache License, Version 2.0 (the "License");
   you may not use this file except in compliance with the License.
   You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License.
"""

from __future__ import absolute_import

import sys
import os

# python 2 and python 3 compatibility library
from six import iteritems

from ..configuration import Configuration
from ..api_client import ApiClient



class SearchServiceApi(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    Ref: https://github.com/swagger-api/swagger-codegen
    """

    def __init__(self, api_client=None):
        config = Configuration()
        if api_client:
            self.api_client = api_client
        else:
            if not config.api_client:
                config.api_client = ApiClient()
            self.api_client = config.api_client


    def search_activate_service(self, id, **kwargs):
        """
        
        

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please define a `callback` function
        to be invoked when receiving the response.
        >>> def callback_function(response):
        >>>     pprint(response)
        >>>

        >>> thread = api.search_activate_service(id, callback=callback_function)



        :param callback function: The callback function
            for asynchronous request. (optional)

        :param str id:  (required)

        :param SearchActivateSettings search_activate_settings: 

        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['id', 'search_activate_settings']
        all_params.append('callback')

        params = locals()
        for key, val in iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method search_activate_service" % key
                )
            params[key] = val
        del params['kwargs']



        # verify the required parameter 'id' is set
        if ('id' not in params) or (params['id'] is None):
            raise ValueError("Missing the required parameter `id` when calling `search_activate_service`")





        resource_path = '/api/Services/Search/{id}/Activate'.replace('{format}', 'json')
        path_params = {}

        if 'id' in params:
            path_params['id'] = params['id']


        query_params = {}


        header_params = {}


        form_params = []
        local_var_files = {}


        body_params = None

        if 'search_activate_settings' in params:
            body_params = params['search_activate_settings']


        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.\
            select_header_accept([])
        if not header_params['Accept']:
            del header_params['Accept']

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.\
            select_header_content_type(['application/json', 'text/json', 'application/json-patch+json'])

        # Authentication setting
        auth_settings = []

        response = self.api_client.call_api(resource_path, 'POST',
                                            path_params,
                                            query_params,
                                            header_params,
                                            body=body_params,
                                            post_params=form_params,
                                            files=local_var_files,
                                            response_type=None,
                                            auth_settings=auth_settings,
                                            callback=params.get('callback'))
        return response


    def search_deactivate_service(self, id, **kwargs):
        """
        
        

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please define a `callback` function
        to be invoked when receiving the response.
        >>> def callback_function(response):
        >>>     pprint(response)
        >>>

        >>> thread = api.search_deactivate_service(id, callback=callback_function)



        :param callback function: The callback function
            for asynchronous request. (optional)

        :param str id:  (required)

        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['id']
        all_params.append('callback')

        params = locals()
        for key, val in iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method search_deactivate_service" % key
                )
            params[key] = val
        del params['kwargs']



        # verify the required parameter 'id' is set
        if ('id' not in params) or (params['id'] is None):
            raise ValueError("Missing the required parameter `id` when calling `search_deactivate_service`")



        resource_path = '/api/Services/Search/{id}/Deactivate'.replace('{format}', 'json')
        path_params = {}

        if 'id' in params:
            path_params['id'] = params['id']


        query_params = {}


        header_params = {}


        form_params = []
        local_var_files = {}


        body_params = None


        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.\
            select_header_accept([])
        if not header_params['Accept']:
            del header_params['Accept']

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.\
            select_header_content_type([])

        # Authentication setting
        auth_settings = []

        response = self.api_client.call_api(resource_path, 'POST',
                                            path_params,
                                            query_params,
                                            header_params,
                                            body=body_params,
                                            post_params=form_params,
                                            files=local_var_files,
                                            response_type=None,
                                            auth_settings=auth_settings,
                                            callback=params.get('callback'))
        return response


    def search_get_service(self, id, **kwargs):
        """
        
        

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please define a `callback` function
        to be invoked when receiving the response.
        >>> def callback_function(response):
        >>>     pprint(response)
        >>>

        >>> thread = api.search_get_service(id, callback=callback_function)



        :param callback function: The callback function
            for asynchronous request. (optional)

        :param str id:  (required)

        :return: SearchService
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['id']
        all_params.append('callback')

        params = locals()
        for key, val in iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method search_get_service" % key
                )
            params[key] = val
        del params['kwargs']



        # verify the required parameter 'id' is set
        if ('id' not in params) or (params['id'] is None):
            raise ValueError("Missing the required parameter `id` when calling `search_get_service`")



        resource_path = '/api/Services/Search/{id}'.replace('{format}', 'json')
        path_params = {}

        if 'id' in params:
            path_params['id'] = params['id']


        query_params = {}


        header_params = {}


        form_params = []
        local_var_files = {}


        body_params = None


        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.\
            select_header_accept([])
        if not header_params['Accept']:
            del header_params['Accept']

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.\
            select_header_content_type([])

        # Authentication setting
        auth_settings = []

        response = self.api_client.call_api(resource_path, 'GET',
                                            path_params,
                                            query_params,
                                            header_params,
                                            body=body_params,
                                            post_params=form_params,
                                            files=local_var_files,
                                            response_type='SearchService',
                                            auth_settings=auth_settings,
                                            callback=params.get('callback'))
        return response


    def search_prepare_service(self, id, **kwargs):
        """
        
        

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please define a `callback` function
        to be invoked when receiving the response.
        >>> def callback_function(response):
        >>>     pprint(response)
        >>>

        >>> thread = api.search_prepare_service(id, callback=callback_function)



        :param callback function: The callback function
            for asynchronous request. (optional)

        :param str id:  (required)

        :param SearchPrepareSettings search_prepare_settings: 

        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['id', 'search_prepare_settings']
        all_params.append('callback')

        params = locals()
        for key, val in iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method search_prepare_service" % key
                )
            params[key] = val
        del params['kwargs']



        # verify the required parameter 'id' is set
        if ('id' not in params) or (params['id'] is None):
            raise ValueError("Missing the required parameter `id` when calling `search_prepare_service`")





        resource_path = '/api/Services/Search/{id}/Prepare'.replace('{format}', 'json')
        path_params = {}

        if 'id' in params:
            path_params['id'] = params['id']


        query_params = {}


        header_params = {}


        form_params = []
        local_var_files = {}


        body_params = None

        if 'search_prepare_settings' in params:
            body_params = params['search_prepare_settings']


        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.\
            select_header_accept([])
        if not header_params['Accept']:
            del header_params['Accept']

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.\
            select_header_content_type(['application/json', 'text/json', 'application/json-patch+json'])

        # Authentication setting
        auth_settings = []

        response = self.api_client.call_api(resource_path, 'POST',
                                            path_params,
                                            query_params,
                                            header_params,
                                            body=body_params,
                                            post_params=form_params,
                                            files=local_var_files,
                                            response_type=None,
                                            auth_settings=auth_settings,
                                            callback=params.get('callback'))
        return response


    def search_service(self, id, **kwargs):
        """
        
        

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please define a `callback` function
        to be invoked when receiving the response.
        >>> def callback_function(response):
        >>>     pprint(response)
        >>>

        >>> thread = api.search_service(id, callback=callback_function)



        :param callback function: The callback function
            for asynchronous request. (optional)

        :param str id:  (required)

        :param SearchRequest request: 

        :return: list[SearchResultWrapper]
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['id', 'request']
        all_params.append('callback')

        params = locals()
        for key, val in iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method search_service" % key
                )
            params[key] = val
        del params['kwargs']



        # verify the required parameter 'id' is set
        if ('id' not in params) or (params['id'] is None):
            raise ValueError("Missing the required parameter `id` when calling `search_service`")





        resource_path = '/api/Services/Search/{id}'.replace('{format}', 'json')
        path_params = {}

        if 'id' in params:
            path_params['id'] = params['id']


        query_params = {}


        header_params = {}


        form_params = []
        local_var_files = {}


        body_params = None

        if 'request' in params:
            body_params = params['request']


        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.\
            select_header_accept([])
        if not header_params['Accept']:
            del header_params['Accept']

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.\
            select_header_content_type(['application/json', 'text/json', 'application/json-patch+json'])

        # Authentication setting
        auth_settings = []

        response = self.api_client.call_api(resource_path, 'POST',
                                            path_params,
                                            query_params,
                                            header_params,
                                            body=body_params,
                                            post_params=form_params,
                                            files=local_var_files,
                                            response_type='list[SearchResultWrapper]',
                                            auth_settings=auth_settings,
                                            callback=params.get('callback'))
        return response


