# coding: utf-8

"""
PrcServiceApi.py
Copyright 2016 SmartBear Software

   Licensed under the Apache License, Version 2.0 (the "License");
   you may not use this file except in compliance with the License.
   You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License.
"""

from __future__ import absolute_import

import sys
import os

# python 2 and python 3 compatibility library
from six import iteritems

from ..configuration import Configuration
from ..api_client import ApiClient



class PrcServiceApi(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    Ref: https://github.com/swagger-api/swagger-codegen
    """

    def __init__(self, api_client=None):
        config = Configuration()
        if api_client:
            self.api_client = api_client
        else:
            if not config.api_client:
                config.api_client = ApiClient()
            self.api_client = config.api_client


    def activate_service(self, id, **kwargs):
        """
        
        

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please define a `callback` function
        to be invoked when receiving the response.
        >>> def callback_function(response):
        >>>     pprint(response)
        >>>

        >>> thread = api.activate_service(id, callback=callback_function)



        :param callback function: The callback function
            for asynchronous request. (optional)

        :param str id:  (required)

        :param PrcActivateSettings prc_activate_settings: 

        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['id', 'prc_activate_settings']
        all_params.append('callback')

        params = locals()
        for key, val in iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method activate_service" % key
                )
            params[key] = val
        del params['kwargs']



        # verify the required parameter 'id' is set
        if ('id' not in params) or (params['id'] is None):
            raise ValueError("Missing the required parameter `id` when calling `activate_service`")





        resource_path = '/api/Services/Prc/{id}/Activate'.replace('{format}', 'json')
        path_params = {}

        if 'id' in params:
            path_params['id'] = params['id']


        query_params = {}


        header_params = {}


        form_params = []
        local_var_files = {}


        body_params = None

        if 'prc_activate_settings' in params:
            body_params = params['prc_activate_settings']


        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.\
            select_header_accept([])
        if not header_params['Accept']:
            del header_params['Accept']

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.\
            select_header_content_type([])

        # Authentication setting
        auth_settings = []

        response = self.api_client.call_api(resource_path, 'POST',
                                            path_params,
                                            query_params,
                                            header_params,
                                            body=body_params,
                                            post_params=form_params,
                                            files=local_var_files,
                                            response_type=None,
                                            auth_settings=auth_settings,
                                            callback=params.get('callback'))
        return response


    def deactivate_service(self, id, **kwargs):
        """
        
        

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please define a `callback` function
        to be invoked when receiving the response.
        >>> def callback_function(response):
        >>>     pprint(response)
        >>>

        >>> thread = api.deactivate_service(id, callback=callback_function)



        :param callback function: The callback function
            for asynchronous request. (optional)

        :param str id:  (required)

        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['id']
        all_params.append('callback')

        params = locals()
        for key, val in iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method deactivate_service" % key
                )
            params[key] = val
        del params['kwargs']



        # verify the required parameter 'id' is set
        if ('id' not in params) or (params['id'] is None):
            raise ValueError("Missing the required parameter `id` when calling `deactivate_service`")



        resource_path = '/api/Services/Prc/{id}/Deactivate'.replace('{format}', 'json')
        path_params = {}

        if 'id' in params:
            path_params['id'] = params['id']


        query_params = {}


        header_params = {}


        form_params = []
        local_var_files = {}


        body_params = None


        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.\
            select_header_accept([])
        if not header_params['Accept']:
            del header_params['Accept']

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.\
            select_header_content_type([])

        # Authentication setting
        auth_settings = []

        response = self.api_client.call_api(resource_path, 'POST',
                                            path_params,
                                            query_params,
                                            header_params,
                                            body=body_params,
                                            post_params=form_params,
                                            files=local_var_files,
                                            response_type=None,
                                            auth_settings=auth_settings,
                                            callback=params.get('callback'))
        return response


    def export_dictionaries(self, id, **kwargs):
        """
        
        

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please define a `callback` function
        to be invoked when receiving the response.
        >>> def callback_function(response):
        >>>     pprint(response)
        >>>

        >>> thread = api.export_dictionaries(id, callback=callback_function)



        :param callback function: The callback function
            for asynchronous request. (optional)

        :param str id:  (required)

        :param ExportDictionariesSettings settings: 

        :return: Process
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['id', 'settings']
        all_params.append('callback')

        params = locals()
        for key, val in iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method export_dictionaries" % key
                )
            params[key] = val
        del params['kwargs']



        # verify the required parameter 'id' is set
        if ('id' not in params) or (params['id'] is None):
            raise ValueError("Missing the required parameter `id` when calling `export_dictionaries`")





        resource_path = '/api/Services/Prc/{id}/ExportDictionaries'.replace('{format}', 'json')
        path_params = {}

        if 'id' in params:
            path_params['id'] = params['id']


        query_params = {}


        header_params = {}


        form_params = []
        local_var_files = {}


        body_params = None

        if 'settings' in params:
            body_params = params['settings']


        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.\
            select_header_accept([])
        if not header_params['Accept']:
            del header_params['Accept']

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.\
            select_header_content_type([])

        # Authentication setting
        auth_settings = []

        response = self.api_client.call_api(resource_path, 'POST',
                                            path_params,
                                            query_params,
                                            header_params,
                                            body=body_params,
                                            post_params=form_params,
                                            files=local_var_files,
                                            response_type='Process',
                                            auth_settings=auth_settings,
                                            callback=params.get('callback'))
        return response


    def get_service(self, id, **kwargs):
        """
        
        

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please define a `callback` function
        to be invoked when receiving the response.
        >>> def callback_function(response):
        >>>     pprint(response)
        >>>

        >>> thread = api.get_service(id, callback=callback_function)



        :param callback function: The callback function
            for asynchronous request. (optional)

        :param str id:  (required)

        :return: PrcService
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['id']
        all_params.append('callback')

        params = locals()
        for key, val in iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method get_service" % key
                )
            params[key] = val
        del params['kwargs']



        # verify the required parameter 'id' is set
        if ('id' not in params) or (params['id'] is None):
            raise ValueError("Missing the required parameter `id` when calling `get_service`")



        resource_path = '/api/Services/Prc/{id}'.replace('{format}', 'json')
        path_params = {}

        if 'id' in params:
            path_params['id'] = params['id']


        query_params = {}


        header_params = {}


        form_params = []
        local_var_files = {}


        body_params = None


        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.\
            select_header_accept([])
        if not header_params['Accept']:
            del header_params['Accept']

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.\
            select_header_content_type([])

        # Authentication setting
        auth_settings = []

        response = self.api_client.call_api(resource_path, 'GET',
                                            path_params,
                                            query_params,
                                            header_params,
                                            body=body_params,
                                            post_params=form_params,
                                            files=local_var_files,
                                            response_type='PrcService',
                                            auth_settings=auth_settings,
                                            callback=params.get('callback'))
        return response


    def prepare_service(self, id, **kwargs):
        """
        
        

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please define a `callback` function
        to be invoked when receiving the response.
        >>> def callback_function(response):
        >>>     pprint(response)
        >>>

        >>> thread = api.prepare_service(id, callback=callback_function)



        :param callback function: The callback function
            for asynchronous request. (optional)

        :param str id:  (required)

        :param PrcPrepareSettings prc_prepare_settings: 

        :return: Process
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['id', 'prc_prepare_settings']
        all_params.append('callback')

        params = locals()
        for key, val in iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method prepare_service" % key
                )
            params[key] = val
        del params['kwargs']



        # verify the required parameter 'id' is set
        if ('id' not in params) or (params['id'] is None):
            raise ValueError("Missing the required parameter `id` when calling `prepare_service`")





        resource_path = '/api/Services/Prc/{id}/Prepare'.replace('{format}', 'json')
        path_params = {}

        if 'id' in params:
            path_params['id'] = params['id']


        query_params = {}


        header_params = {}


        form_params = []
        local_var_files = {}


        body_params = None

        if 'prc_prepare_settings' in params:
            body_params = params['prc_prepare_settings']


        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.\
            select_header_accept([])
        if not header_params['Accept']:
            del header_params['Accept']

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.\
            select_header_content_type([])

        # Authentication setting
        auth_settings = []

        response = self.api_client.call_api(resource_path, 'POST',
                                            path_params,
                                            query_params,
                                            header_params,
                                            body=body_params,
                                            post_params=form_params,
                                            files=local_var_files,
                                            response_type='Process',
                                            auth_settings=auth_settings,
                                            callback=params.get('callback'))
        return response


    def recommend_service(self, id, **kwargs):
        """
        
        

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please define a `callback` function
        to be invoked when receiving the response.
        >>> def callback_function(response):
        >>>     pprint(response)
        >>>

        >>> thread = api.recommend_service(id, callback=callback_function)



        :param callback function: The callback function
            for asynchronous request. (optional)

        :param str id:  (required)

        :param PrcRecommendationRequest request: 

        :return: list[PrcRecommendationResult]
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['id', 'request']
        all_params.append('callback')

        params = locals()
        for key, val in iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method recommend_service" % key
                )
            params[key] = val
        del params['kwargs']



        # verify the required parameter 'id' is set
        if ('id' not in params) or (params['id'] is None):
            raise ValueError("Missing the required parameter `id` when calling `recommend_service`")





        resource_path = '/api/Services/Prc/{id}/Recommend'.replace('{format}', 'json')
        path_params = {}

        if 'id' in params:
            path_params['id'] = params['id']


        query_params = {}


        header_params = {}


        form_params = []
        local_var_files = {}


        body_params = None

        if 'request' in params:
            body_params = params['request']


        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.\
            select_header_accept([])
        if not header_params['Accept']:
            del header_params['Accept']

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.\
            select_header_content_type([])

        # Authentication setting
        auth_settings = []

        response = self.api_client.call_api(resource_path, 'POST',
                                            path_params,
                                            query_params,
                                            header_params,
                                            body=body_params,
                                            post_params=form_params,
                                            files=local_var_files,
                                            response_type='list[PrcRecommendationResult]',
                                            auth_settings=auth_settings,
                                            callback=params.get('callback'))
        return response


