# coding: utf-8

"""
Copyright 2016 SmartBear Software

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.

    Ref: https://github.com/swagger-api/swagger-codegen
"""



from pprint import pformat
from six import iteritems


class DataSet(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self):
        """
        DataSet - a model defined in Swagger

        :param dict swaggerTypes: The key is attribute name
                                  and the value is attribute type.
        :param dict attributeMap: The key is attribute name
                                  and the value is json key in definition.
        """
        self.swagger_types = {
            'name': 'str',
            'n_gram_count': 'int',
            'id_field': 'str',
            'tag_field': 'str',
            'interpreted_fields': 'list[str]',
            'statistics': 'DataSetStats',
            'sample_document': 'object',
            'schema': 'object'
        }

        self.attribute_map = {
            'name': 'Name',
            'n_gram_count': 'NGramCount',
            'id_field': 'IdField',
            'tag_field': 'TagField',
            'interpreted_fields': 'InterpretedFields',
            'statistics': 'Statistics',
            'sample_document': 'SampleDocument',
            'schema': 'Schema'
        }


        self._name = None

        self._n_gram_count = None

        self._id_field = None

        self._tag_field = None

        self._interpreted_fields = None

        self._statistics = None

        self._sample_document = None

        self._schema = None



    @property
    def name(self):
        """
        Gets the name of this DataSet.
        Name of your dataset. Can contains just A-Z letters, numbers, _ (underscore) and - (hyphen) without any space. This field is unique

        :return: The name of this DataSet.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """
        Sets the name of this DataSet.
        Name of your dataset. Can contains just A-Z letters, numbers, _ (underscore) and - (hyphen) without any space. This field is unique

        :param name: The name of this DataSet.
        :type: str
        """
        self._name = name


    @property
    def n_gram_count(self):
        """
        Gets the n_gram_count of this DataSet.
        To deeper analyze your text, a dataset uses ngram to index your document. You can set the ngramcount from 1 to 6

        :return: The n_gram_count of this DataSet.
        :rtype: int
        """
        return self._n_gram_count

    @n_gram_count.setter
    def n_gram_count(self, n_gram_count):
        """
        Sets the n_gram_count of this DataSet.
        To deeper analyze your text, a dataset uses ngram to index your document. You can set the ngramcount from 1 to 6

        :param n_gram_count: The n_gram_count of this DataSet.
        :type: int
        """
        self._n_gram_count = n_gram_count


    @property
    def id_field(self):
        """
        Gets the id_field of this DataSet.
        To identify a document you need to use IDs. You can use your own conventions to name your ID field, but in the settings you need to provide the field name of the id field from your sample document. Can contains just A-Z letters, numbers, _ (underscore) and - (hyphen) without any space

        :return: The id_field of this DataSet.
        :rtype: str
        """
        return self._id_field

    @id_field.setter
    def id_field(self, id_field):
        """
        Sets the id_field of this DataSet.
        To identify a document you need to use IDs. You can use your own conventions to name your ID field, but in the settings you need to provide the field name of the id field from your sample document. Can contains just A-Z letters, numbers, _ (underscore) and - (hyphen) without any space

        :param id_field: The id_field of this DataSet.
        :type: str
        """
        self._id_field = id_field


    @property
    def tag_field(self):
        """
        Gets the tag_field of this DataSet.
        For text categorization, we provide a predefined document field to store your tags (or categories). If your documents are related to tags or categories, please insert here the tags field name from your sample JSON. Can contains just A-Z letters, numbers, _ (underscore) and - (hyphen) without any space

        :return: The tag_field of this DataSet.
        :rtype: str
        """
        return self._tag_field

    @tag_field.setter
    def tag_field(self, tag_field):
        """
        Sets the tag_field of this DataSet.
        For text categorization, we provide a predefined document field to store your tags (or categories). If your documents are related to tags or categories, please insert here the tags field name from your sample JSON. Can contains just A-Z letters, numbers, _ (underscore) and - (hyphen) without any space

        :param tag_field: The tag_field of this DataSet.
        :type: str
        """
        self._tag_field = tag_field


    @property
    def interpreted_fields(self):
        """
        Gets the interpreted_fields of this DataSet.
        For text analysis, you can set those document fields that contains useful text content. Slamby is doing ngram analysis and text process related works on these fields. How to decide which field you need to set here? Only the interpreted field can be a part of text analyzes. To provide these fields just simply insert the needed text fields from your JSON document. Field names can contain just A-Z letters, numbers, _ (underscore) and - (hyphen) without any space

        :return: The interpreted_fields of this DataSet.
        :rtype: list[str]
        """
        return self._interpreted_fields

    @interpreted_fields.setter
    def interpreted_fields(self, interpreted_fields):
        """
        Sets the interpreted_fields of this DataSet.
        For text analysis, you can set those document fields that contains useful text content. Slamby is doing ngram analysis and text process related works on these fields. How to decide which field you need to set here? Only the interpreted field can be a part of text analyzes. To provide these fields just simply insert the needed text fields from your JSON document. Field names can contain just A-Z letters, numbers, _ (underscore) and - (hyphen) without any space

        :param interpreted_fields: The interpreted_fields of this DataSet.
        :type: list[str]
        """
        self._interpreted_fields = interpreted_fields


    @property
    def statistics(self):
        """
        Gets the statistics of this DataSet.
        These are read-only calculated values

        :return: The statistics of this DataSet.
        :rtype: DataSetStats
        """
        return self._statistics

    @statistics.setter
    def statistics(self, statistics):
        """
        Sets the statistics of this DataSet.
        These are read-only calculated values

        :param statistics: The statistics of this DataSet.
        :type: DataSetStats
        """
        self._statistics = statistics


    @property
    def sample_document(self):
        """
        Gets the sample_document of this DataSet.
        Using flexible document schema, you can store all of your required data inside one simple dataset. To create a dataset with your required schema you can provide a sample document. The schema is flexible; the only requirement is using standard JSON format. Field names can contain just A-Z letters, numbers, _ (underscore) and - (hyphen) without any space

        :return: The sample_document of this DataSet.
        :rtype: object
        """
        return self._sample_document

    @sample_document.setter
    def sample_document(self, sample_document):
        """
        Sets the sample_document of this DataSet.
        Using flexible document schema, you can store all of your required data inside one simple dataset. To create a dataset with your required schema you can provide a sample document. The schema is flexible; the only requirement is using standard JSON format. Field names can contain just A-Z letters, numbers, _ (underscore) and - (hyphen) without any space

        :param sample_document: The sample_document of this DataSet.
        :type: object
        """
        self._sample_document = sample_document


    @property
    def schema(self):
        """
        Gets the schema of this DataSet.
        Using flexible document schema, you can store all of your required data inside one simple dataset. To create a dataset with your required schema you can provide a schema. The schema is flexible. Field names can contain just A-Z letters, numbers, _ (underscore) and - (hyphen) without any space

        :return: The schema of this DataSet.
        :rtype: object
        """
        return self._schema

    @schema.setter
    def schema(self, schema):
        """
        Sets the schema of this DataSet.
        Using flexible document schema, you can store all of your required data inside one simple dataset. To create a dataset with your required schema you can provide a schema. The schema is flexible. Field names can contain just A-Z letters, numbers, _ (underscore) and - (hyphen) without any space

        :param schema: The schema of this DataSet.
        :type: object
        """
        self._schema = schema


    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other



