# coding: utf-8

"""
Copyright 2016 SmartBear Software

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.

    Ref: https://github.com/swagger-api/swagger-codegen
"""



from pprint import pformat
from six import iteritems


class PrcRecommendationRequest(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self):
        """
        PrcRecommendationRequest - a model defined in Swagger

        :param dict swaggerTypes: The key is attribute name
                                  and the value is attribute type.
        :param dict attributeMap: The key is attribute name
                                  and the value is json key in definition.
        """
        self.swagger_types = {
            'text': 'str',
            'count': 'int',
            'need_document_in_result': 'bool',
            'tag_id': 'str',
            'filter': 'Filter',
            'weights': 'list[Weight]'
        }

        self.attribute_map = {
            'text': 'Text',
            'count': 'Count',
            'need_document_in_result': 'NeedDocumentInResult',
            'tag_id': 'TagId',
            'filter': 'Filter',
            'weights': 'Weights'
        }


        self._text = None

        self._count = None

        self._need_document_in_result = None

        self._tag_id = None

        self._filter = None

        self._weights = None



    @property
    def text(self):
        """
        Gets the text of this PrcRecommendationRequest.


        :return: The text of this PrcRecommendationRequest.
        :rtype: str
        """
        return self._text

    @text.setter
    def text(self, text):
        """
        Sets the text of this PrcRecommendationRequest.


        :param text: The text of this PrcRecommendationRequest.
        :type: str
        """
        self._text = text


    @property
    def count(self):
        """
        Gets the count of this PrcRecommendationRequest.


        :return: The count of this PrcRecommendationRequest.
        :rtype: int
        """
        return self._count

    @count.setter
    def count(self, count):
        """
        Sets the count of this PrcRecommendationRequest.


        :param count: The count of this PrcRecommendationRequest.
        :type: int
        """
        self._count = count


    @property
    def need_document_in_result(self):
        """
        Gets the need_document_in_result of this PrcRecommendationRequest.


        :return: The need_document_in_result of this PrcRecommendationRequest.
        :rtype: bool
        """
        return self._need_document_in_result

    @need_document_in_result.setter
    def need_document_in_result(self, need_document_in_result):
        """
        Sets the need_document_in_result of this PrcRecommendationRequest.


        :param need_document_in_result: The need_document_in_result of this PrcRecommendationRequest.
        :type: bool
        """
        self._need_document_in_result = need_document_in_result


    @property
    def tag_id(self):
        """
        Gets the tag_id of this PrcRecommendationRequest.


        :return: The tag_id of this PrcRecommendationRequest.
        :rtype: str
        """
        return self._tag_id

    @tag_id.setter
    def tag_id(self, tag_id):
        """
        Sets the tag_id of this PrcRecommendationRequest.


        :param tag_id: The tag_id of this PrcRecommendationRequest.
        :type: str
        """
        self._tag_id = tag_id


    @property
    def filter(self):
        """
        Gets the filter of this PrcRecommendationRequest.


        :return: The filter of this PrcRecommendationRequest.
        :rtype: Filter
        """
        return self._filter

    @filter.setter
    def filter(self, filter):
        """
        Sets the filter of this PrcRecommendationRequest.


        :param filter: The filter of this PrcRecommendationRequest.
        :type: Filter
        """
        self._filter = filter


    @property
    def weights(self):
        """
        Gets the weights of this PrcRecommendationRequest.


        :return: The weights of this PrcRecommendationRequest.
        :rtype: list[Weight]
        """
        return self._weights

    @weights.setter
    def weights(self, weights):
        """
        Sets the weights of this PrcRecommendationRequest.


        :param weights: The weights of this PrcRecommendationRequest.
        :type: list[Weight]
        """
        self._weights = weights


    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other



